export const ITEMS_PER_PAGE = 7;
export const PAGINATION_TIMEOUT = 5 * 60 * 1000; // 5 minutes
export const MAX_RECENT_LINKS = 30;
export const DEFAULT_FREQUENCY_MINUTES = 15;
export const MIN_FREQUENCY_MINUTES = 3;
export const MAX_FREQUENCY_MINUTES = 1440;
export const FAILURE_NOTIFICATION_THRESHOLD = 10; // Increased from 4 to delay notifications
export const FAILURE_QUIET_PERIOD_HOURS = 24; // Quiet period after threshold is reached
export const MAX_ITEM_HOURS = 12;
export const BASE_MINUTES = 15; // Increased from 5 for more aggressive initial backoff
export const MAX_MINUTES = 1440; // Increased from 360 (6 hours) to 24 hours max
export const MODEL_NAME = 'google/gemini-2.0-flash-lite-001';
export const CATEGORY_BACKOFF_COORDINATION_FACTOR = 0.5; // When one feed in category fails, apply 50% of its backoff to others
