export const ITEMS_PER_PAGE = 7;
export const PAGINATION_TIMEOUT = 5 * 60 * 1000; // 5 minutes
export const MAX_RECENT_LINKS = 30;
export const DEFAULT_FREQUENCY_MINUTES = 15;
export const MIN_FREQUENCY_MINUTES = 1;
export const MAX_FREQUENCY_MINUTES = 1440;
export const FAILURE_NOTIFICATION_THRESHOLD = 5;
export const MAX_ITEM_HOURS = 12;
export const BASE_MINUTES = 5;
export const MAX_MINUTES = 360; // 6 hours
export const MODEL_NAME = 'google/gemini-2.0-flash-001';
