/**
 * Snapshots the production Postgres database into a SQL file that can be
 * loaded into D1. Re-runnable: the generated SQL deletes existing rows first,
 * so run it once now and once more at cutover time for a fresh copy.
 *
 * Usage (from workers/bot):
 *   bun run db:snapshot     # reads DATABASE_URL from ../../.env
 *   bun run db:load-snapshot
 *
 * Must run with TZ=UTC (the db:snapshot script sets it): the pg columns are
 * timezone-naive UTC, and postgres-js parses them in the process timezone —
 * any other TZ shifts every timestamp.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import postgres from 'postgres';

function loadDatabaseUrl(): string {
    if (process.env.DATABASE_URL) return process.env.DATABASE_URL;
    const envFile = readFileSync(join(import.meta.dirname, '../../../.env'), 'utf8');
    const match = envFile.match(/^DATABASE_URL=["']?([^"'\n]+)["']?\s*$/m);
    if (!match) throw new Error('DATABASE_URL not found in env or ../../.env');
    return match[1];
}

type SqlValue = string | number | boolean | Date | null;

function lit(value: SqlValue): string {
    if (value === null || value === undefined) return 'NULL';
    if (value instanceof Date) return String(value.getTime());
    if (typeof value === 'boolean') return value ? '1' : '0';
    if (typeof value === 'number') return String(value);
    return `'${value.replace(/'/g, "''")}'`;
}

function insertStatements(table: string, columns: string[], rows: Record<string, SqlValue>[]): string[] {
    const statements: string[] = [];
    // Batch inserts, capped by statement byte size (D1 rejects oversized statements
    // with SQLITE_TOOBIG — rows with long summaries can be tens of KB each).
    const MAX_STATEMENT_BYTES = 80_000;
    let batch: string[] = [];
    let batchBytes = 0;
    const flush = (): void => {
        if (batch.length === 0) return;
        statements.push(`INSERT INTO ${table} (${columns.join(',')}) VALUES\n${batch.join(',\n')};`);
        batch = [];
        batchBytes = 0;
    };
    for (const row of rows) {
        const tuple = `(${columns.map(col => lit(row[col])).join(',')})`;
        if (batch.length > 0 && batchBytes + tuple.length > MAX_STATEMENT_BYTES) flush();
        batch.push(tuple);
        batchBytes += tuple.length;
    }
    flush();
    return statements;
}

const sql = postgres(loadDatabaseUrl(), {
    ssl: 'prefer',
    max: 1,
    prepare: false,
});

const feeds = await sql`SELECT * FROM feeds ORDER BY created_at`;
const failures = await sql`SELECT * FROM feed_failures ORDER BY id`;
const categories = await sql`SELECT * FROM categories ORDER BY id`;
const guilds = await sql`SELECT * FROM guilds ORDER BY guild_id`;
await sql.end();

const out: string[] = [
    '-- Generated by scripts/export-postgres.ts — full snapshot, replaces existing data.',
    'DELETE FROM feed_failures;',
    'DELETE FROM feeds;',
    'DELETE FROM categories;',
    'DELETE FROM guilds;',
];

out.push(
    ...insertStatements(
        'feeds',
        [
            'id', 'url', 'channel_id', 'guild_id', 'nickname', 'category', 'added_by',
            'frequency_override_minutes', 'last_checked', 'last_item_guid',
            'consecutive_failures', 'created_at', 'summarize', 'use_archive_links',
            'suppress_link_preview', 'last_article_summary', 'last_comments_summary',
            'recent_links', 'last_failure_notification_at', 'last_error_message_at',
            'backoff_until', 'ignore_errors', 'disable_failure_notifications',
            'disabled', 'language', 'skip_youtube_shorts', 'skip_youtube_livestreams',
        ],
        feeds
    ),
    ...insertStatements(
        'feed_failures',
        ['id', 'feed_id', 'timestamp', 'error_message'],
        failures
    ),
    ...insertStatements(
        'categories',
        ['id', 'guild_id', 'name', 'name_lower', 'frequency_minutes'],
        categories
    ),
    ...insertStatements(
        'guilds',
        ['guild_id', 'language', 'created_at', 'updated_at'],
        guilds
    )
);

const outPath = join(import.meta.dirname, '../migrations/data-snapshot.sql');
writeFileSync(outPath, out.join('\n') + '\n');
console.log(
    `Wrote ${outPath}: ${feeds.length} feeds, ${failures.length} failures, ` +
        `${categories.length} categories, ${guilds.length} guilds`
);
